services:
  cantuscatholici-api:
    image: '${DOCKER_IMAGE?Variable not set}:${TAG-latest}'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=cantuscatholici
      - POSTGRES_DB=cantuscatholici
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0"]
    volumes:
      - ./app:/app/app:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: compose.yaml
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:17.5-alpine
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=cantuscatholici
      - POSTGRES_DB=cantuscatholici
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - cantuscatholici-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cantuscatholici -d cantuscatholici"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  cantuscatholici-data:
