"""inital db schema

Revision ID: 7acb1f0aa6e5
Revises:
Create Date: 2025-10-02 13:12:47.322691

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7acb1f0aa6e5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_base",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_verses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("lyrics", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
    )
    op.create_table(
        "static_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["content_base.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["tag_categories.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "mscz_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("c_mscz_file_id", sa.Integer(), nullable=False),
        sa.Column("c_svg_file_id", sa.Integer(), nullable=False),
        sa.Column("pdf_file_id", sa.Integer(), nullable=False),
        sa.Column("mp3_file_id", sa.Integer(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["c_mscz_file_id"], ["static_content.id"]),
        sa.ForeignKeyConstraint(["c_svg_file_id"], ["static_content.id"]),
        sa.ForeignKeyConstraint(["id"], ["content_base.id"]),
        sa.ForeignKeyConstraint(["mp3_file_id"], ["static_content.id"]),
        sa.ForeignKeyConstraint(["pdf_file_id"], ["static_content.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("avatar", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["avatar"], ["static_content.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_parts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("verses_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.ForeignKeyConstraint(["verses_id"], ["song_verses.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["part_id"], ["song_parts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["persons.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["user_roles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("mobile"),
    )
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("added_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["id"], ["persons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("commenter_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["commenter_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("mscz_id", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("added_by_user_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["file_id"], ["static_content.id"]),
        sa.ForeignKeyConstraint(["id"], ["content_base.id"]),
        sa.ForeignKeyConstraint(["mscz_id"], ["mscz_content.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_mr",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reviewable_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("redactor_id", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["comments"], ["review_comments.id"]),
        sa.ForeignKeyConstraint(["redactor_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["reviewable_id"], ["content_base.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("added_by_user_id", sa.Integer(), nullable=True),
        sa.Column("search_tag_id", sa.Integer(), nullable=True),
        sa.Column("song_part_id", sa.Integer(), nullable=True),
        sa.Column("song_order_id", sa.Integer(), nullable=True),
        sa.Column("mscz_id", sa.Integer(), nullable=True),
        sa.Column("user_content_id", sa.Integer(), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column("lang_tag_id", sa.Integer(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_edit_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["author"], ["persons.id"]),
        sa.ForeignKeyConstraint(["id"], ["content_base.id"]),
        sa.ForeignKeyConstraint(["lang_tag_id"], ["tags.id"]),
        sa.ForeignKeyConstraint(["mscz_id"], ["mscz_content.id"]),
        sa.ForeignKeyConstraint(["related_id"], ["songs.id"]),
        sa.ForeignKeyConstraint(["search_tag_id"], ["tags.id"]),
        sa.ForeignKeyConstraint(["song_order_id"], ["song_order.id"]),
        sa.ForeignKeyConstraint(["song_part_id"], ["song_parts.id"]),
        sa.ForeignKeyConstraint(["user_content_id"], ["user_content.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("api_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("recommended_song_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["recommended_song_id"], ["songs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_entry")
    op.drop_table("songs")
    op.drop_table("song_mr")
    op.drop_table("user_content")
    op.drop_table("review_comments")
    op.drop_table("authors")
    op.drop_table("users")
    op.drop_table("song_order")
    op.drop_table("song_parts")
    op.drop_table("persons")
    op.drop_table("mscz_content")
    op.drop_table("tags")
    op.drop_table("static_content")
    op.drop_table("user_roles")
    op.drop_table("tag_categories")
    op.drop_table("song_verses")
    op.drop_table("content_base")
    # ### end Alembic commands ###
