name: Test
on: [ pull_request ]

jobs:
  test-migration:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: localhost
      DOCKER_IMAGE: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}
      LOG_DB_ENGINE_ECHO: True
      APP_STATIC_CONTENT_PREFIX: /data/cantuscatholici/dummy
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/project-setup
      - run: docker compose down -v --remove-orphans
      - name: Setup database service
        run: docker compose up -d db
      - name: Pytest migrations
        run: uv run pytest -m alembic
      - run: docker compose down -v --remove-orphans

  test:
    runs-on: ubuntu-latest
    needs: [test-migration]
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: localhost
      DOCKER_IMAGE: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}
      LOG_DB_ENGINE_ECHO: True
      APP_STATIC_CONTENT_PREFIX: /data/cantuscatholici/dummy
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/project-setup
      - run: docker compose down -v --remove-orphans
      - name: Setup database service
        run: docker compose up -d db
      - name: Pytest app
        run: uv run pytest -m "not alembic"
      - run: docker compose down -v --remove-orphans
